"""AOI simulator — a template-differencing defect detector.

This reproduces how real automated optical inspection works: the board under
test is compared against a known-good golden board, and anything that differs
beyond a threshold is flagged for review. It is deliberately cheap and tuned
for recall, which is exactly why real AOI over-flags.

The candidates it emits are the input to the re-verification model. Candidates
that overlap a ground-truth defect are real; the rest are **false calls** —
generated by a real algorithm on real images rather than fabricated.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import cv2
import numpy as np

from aoi_agent.aoi.registration import align


@dataclass(frozen=True)
class Candidate:
    """A region the AOI simulator flagged for review."""

    x1: int
    y1: int
    x2: int
    y2: int
    area: int

    @property
    def box(self) -> tuple[int, int, int, int]:
        return (self.x1, self.y1, self.x2, self.y2)


@dataclass(frozen=True)
class Perturbation:
    """Real-world disturbances that cause AOI false calls.

    Production AOI never sees a perfectly registered, perfectly lit board.
    Sub-pixel stage repeatability, sensor noise and lamp ageing all shift the
    tested image relative to the golden template, and every such shift shows up
    in the difference image as something that looks like a defect.

    DeepPCB ships pre-aligned, binarised images, so these disturbances have
    already been engineered away. Adding them back is restoring the operating
    conditions, not corrupting the data.
    """

    max_shift_px: int = 0
    max_rotation_deg: float = 0.0
    """A board placed slightly crooked, which is the disturbance a translation
    cannot describe.

    Added 2026-08-24, when `aoi/registration.py` needed something it could not
    already invert: phase correlation recovers a pure translation exactly, so a
    registration stage measured only against `max_shift_px` measures the
    arithmetic that produced the shift. HRIPCB's authors rotated half their
    images for the same reason -- a board is not misplaced along one axis, it is
    misplaced.
    """

    noise_sigma: float = 0.0
    gain: float = 1.0
    seed: int | None = None

    @property
    def enabled(self) -> bool:
        return (
            self.max_shift_px > 0
            or self.max_rotation_deg > 0
            or self.noise_sigma > 0
            or self.gain != 1.0
        )


@dataclass
class DetectorConfig:
    """Tuning knobs for the differencing detector."""

    threshold: int = 60
    """Absolute grey-level difference above which a pixel is suspicious."""

    open_kernel: int = 3
    """Morphological opening removes isolated speckle from JPEG artefacts.

    It also erases the one- and two-pixel slivers that misregistration leaves
    along every trace edge, which is what keeps the candidate count workable.
    The trade-off is that this detector tolerates misalignment better than a
    real AOI does, so the false calls it produces come from other causes and
    the counts are conservative. Set to ``0`` to see the registration
    artefacts.

    It also erases seven real defects on the test split -- every one of them a
    sub-3px notch, whisker or filament whose difference blob is 24 to 133
    pixels and which a 3x3 opening takes to zero. Those seven are the whole of
    this line's unrecoverable escape rate. The trade was swept on 2026-08-23
    and the value kept: recovering them costs thousands of additional false
    calls per defect the re-verifier actually keeps, and multiplies the
    candidate count under misregistration, which is the condition the opening
    exists for. The numbers are in docs/benchmarks.md, from
    `scripts/opening_kernel_sweep.py`. Do not lower this without re-running
    that sweep -- it is a trade, and it has a curve.
    """

    register: bool = False
    """Align the tested board to its template before differencing.

    Off by default, and the default is the honest one: DeepPCB arrives
    pre-registered, so turning this on changes the candidate population the
    re-verifier was trained and swept on. Doing that without the full retrain
    chain leaves a new detector running on the old model's operating point,
    which is the silent failure `.claude/skills/retraining-the-reverifier`
    exists to prevent.

    What it buys, measured over the 500-pair test split: candidates 18.1 -> 16.1
    a board and AOI recall 95.0% -> 95.6%, because "pre-registered" was never
    "aligned" -- the median residual on an untouched pair is 0.48 px. What it
    cannot do is rotation. See `scripts/registration_recovery.py`.
    """

    open_shape: str = "rect"
    """Structuring element for the opening: ``rect``, ``cross`` or ``ellipse``.

    Only the sweep uses anything but ``rect``. A 3x3 cross survives on five
    cells in a plus where a 3x3 square needs all nine, so it keeps features a
    square erases -- fewer of them than a 2x2 square does, and at a lower
    false-call cost. Neither was taken; see the sweep.
    """

    dilate_kernel: int = 5
    """Dilation merges pixels of one defect into a single blob."""

    min_area: int = 25
    """Blobs smaller than this are sensor noise, not features."""

    max_area: int = 40_000
    """Blobs larger than this indicate a registration failure, not a defect."""

    pad: int = 4
    """Padding added around each blob so the patch keeps some context."""


#: Structuring-element shapes the opening understands. ``rect`` is what ships;
#: the others exist so the opening-kernel sweep can price them against it.
OPENING_SHAPES = {
    "rect": cv2.MORPH_RECT,
    "cross": cv2.MORPH_CROSS,
    "ellipse": cv2.MORPH_ELLIPSE,
}


def opening_element(config: DetectorConfig) -> np.ndarray:
    """The structuring element the opening uses, from the config."""
    try:
        shape = OPENING_SHAPES[config.open_shape]
    except KeyError:
        raise ValueError(
            f"unknown open_shape {config.open_shape!r}; "
            f"expected one of {sorted(OPENING_SHAPES)}"
        ) from None
    return cv2.getStructuringElement(shape, (config.open_kernel, config.open_kernel))


def apply_perturbation(
    template: np.ndarray, perturbation: Perturbation
) -> np.ndarray:
    """Return a copy of ``template`` degraded to production conditions."""
    if not perturbation.enabled:
        return template

    rng = np.random.default_rng(perturbation.seed)
    out = template.astype(np.float32)

    if perturbation.max_shift_px > 0 or perturbation.max_rotation_deg > 0:
        dx, dy = (
            rng.integers(
                -perturbation.max_shift_px, perturbation.max_shift_px + 1, size=2
            )
            if perturbation.max_shift_px > 0
            else (0, 0)
        )
        angle = (
            float(rng.uniform(-perturbation.max_rotation_deg,
                              perturbation.max_rotation_deg))
            if perturbation.max_rotation_deg > 0
            else 0.0
        )
        # One warp for both, about the image centre: two warps would interpolate
        # twice and blur a board that a line only ever placed once.
        centre = (out.shape[1] / 2.0, out.shape[0] / 2.0)
        matrix = cv2.getRotationMatrix2D(centre, angle, 1.0)
        matrix[0, 2] += dx
        matrix[1, 2] += dy
        out = cv2.warpAffine(
            out,
            matrix,
            (out.shape[1], out.shape[0]),
            flags=cv2.INTER_LINEAR,
            borderMode=cv2.BORDER_REPLICATE,
        )

    if perturbation.gain != 1.0:
        out *= perturbation.gain

    if perturbation.noise_sigma > 0:
        out += rng.normal(0.0, perturbation.noise_sigma, size=out.shape)

    return np.clip(out, 0, 255).astype(np.uint8)


def detect(
    template: np.ndarray,
    test: np.ndarray,
    config: DetectorConfig | None = None,
    perturbation: Perturbation | None = None,
) -> list[Candidate]:
    """Flag every region where the tested board differs from its template.

    ``config.register`` and ``perturbation`` do not compose, and asking for both
    raises rather than returning boxes in a frame nobody expects. The
    perturbation moves the *template*, which is the frame the annotations are
    expressed in; registration moves the *test* onto whatever template it is
    given. Together they would put candidates in the perturbed template's
    coordinates and match them against boxes drawn in the original's, which is
    an error that looks like a recall collapse rather than like a bug.
    `scripts/registration_recovery.py` wants both and does them itself, in the
    order that keeps the annotation frame: perturb the test, align it back.
    """
    config = config or DetectorConfig()

    if perturbation is not None and config.register:
        raise ValueError(
            "detect(register=True) and a perturbation put candidates in "
            "different frames -- see the docstring. Perturb the test image and "
            "call `registration.align` yourself, as registration_recovery does."
        )

    if perturbation is not None:
        template = apply_perturbation(template, perturbation)

    if config.register:
        test, _alignment = align(template, test)

    diff = cv2.absdiff(test, template)
    _, mask = cv2.threshold(diff, config.threshold, 255, cv2.THRESH_BINARY)

    if config.open_kernel > 0:
        mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, opening_element(config))

    if config.dilate_kernel > 0:
        kernel = np.ones((config.dilate_kernel, config.dilate_kernel), np.uint8)
        mask = cv2.dilate(mask, kernel)

    count, _, stats, _ = cv2.connectedComponentsWithStats(mask, connectivity=8)

    height, width = mask.shape
    candidates = []
    for label in range(1, count):  # label 0 is the background
        x, y, w, h, area = stats[label]
        if area < config.min_area or area > config.max_area:
            continue
        candidates.append(
            Candidate(
                x1=max(0, x - config.pad),
                y1=max(0, y - config.pad),
                x2=min(width, x + w + config.pad),
                y2=min(height, y + h + config.pad),
                area=int(area),
            )
        )
    return candidates
