"""AOI simulator — a template-differencing defect detector.

This reproduces how real automated optical inspection works: the board under
test is compared against a known-good golden board, and anything that differs
beyond a threshold is flagged for review. It is deliberately cheap and tuned
for recall, which is exactly why real AOI over-flags.

The candidates it emits are the input to the re-verification model. Candidates
that overlap a ground-truth defect are real; the rest are **false calls** —
generated by a real algorithm on real images rather than fabricated.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import cv2
import numpy as np


@dataclass(frozen=True)
class Candidate:
    """A region the AOI simulator flagged for review."""

    x1: int
    y1: int
    x2: int
    y2: int
    area: int

    @property
    def box(self) -> tuple[int, int, int, int]:
        return (self.x1, self.y1, self.x2, self.y2)


@dataclass(frozen=True)
class Perturbation:
    """Real-world disturbances that cause AOI false calls.

    Production AOI never sees a perfectly registered, perfectly lit board.
    Sub-pixel stage repeatability, sensor noise and lamp ageing all shift the
    tested image relative to the golden template, and every such shift shows up
    in the difference image as something that looks like a defect.

    DeepPCB ships pre-aligned, binarised images, so these disturbances have
    already been engineered away. Adding them back is restoring the operating
    conditions, not corrupting the data.
    """

    max_shift_px: int = 0
    noise_sigma: float = 0.0
    gain: float = 1.0
    seed: int | None = None

    @property
    def enabled(self) -> bool:
        return self.max_shift_px > 0 or self.noise_sigma > 0 or self.gain != 1.0


@dataclass
class DetectorConfig:
    """Tuning knobs for the differencing detector."""

    threshold: int = 60
    """Absolute grey-level difference above which a pixel is suspicious."""

    open_kernel: int = 3
    """Morphological opening removes isolated speckle from JPEG artefacts.

    It also erases the one- and two-pixel slivers that misregistration leaves
    along every trace edge, which is what keeps the candidate count workable.
    The trade-off is that this detector tolerates misalignment better than a
    real AOI does, so the false calls it produces come from other causes and
    the counts are conservative. Set to ``0`` to see the registration
    artefacts.
    """

    dilate_kernel: int = 5
    """Dilation merges pixels of one defect into a single blob."""

    min_area: int = 25
    """Blobs smaller than this are sensor noise, not features."""

    max_area: int = 40_000
    """Blobs larger than this indicate a registration failure, not a defect."""

    pad: int = 4
    """Padding added around each blob so the patch keeps some context."""


def apply_perturbation(
    template: np.ndarray, perturbation: Perturbation
) -> np.ndarray:
    """Return a copy of ``template`` degraded to production conditions."""
    if not perturbation.enabled:
        return template

    rng = np.random.default_rng(perturbation.seed)
    out = template.astype(np.float32)

    if perturbation.max_shift_px > 0:
        dx, dy = rng.integers(
            -perturbation.max_shift_px, perturbation.max_shift_px + 1, size=2
        )
        matrix = np.float32([[1, 0, dx], [0, 1, dy]])
        out = cv2.warpAffine(
            out,
            matrix,
            (out.shape[1], out.shape[0]),
            flags=cv2.INTER_LINEAR,
            borderMode=cv2.BORDER_REPLICATE,
        )

    if perturbation.gain != 1.0:
        out *= perturbation.gain

    if perturbation.noise_sigma > 0:
        out += rng.normal(0.0, perturbation.noise_sigma, size=out.shape)

    return np.clip(out, 0, 255).astype(np.uint8)


def detect(
    template: np.ndarray,
    test: np.ndarray,
    config: DetectorConfig | None = None,
    perturbation: Perturbation | None = None,
) -> list[Candidate]:
    """Flag every region where the tested board differs from its template."""
    config = config or DetectorConfig()

    if perturbation is not None:
        template = apply_perturbation(template, perturbation)

    diff = cv2.absdiff(test, template)
    _, mask = cv2.threshold(diff, config.threshold, 255, cv2.THRESH_BINARY)

    if config.open_kernel > 0:
        kernel = np.ones((config.open_kernel, config.open_kernel), np.uint8)
        mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)

    if config.dilate_kernel > 0:
        kernel = np.ones((config.dilate_kernel, config.dilate_kernel), np.uint8)
        mask = cv2.dilate(mask, kernel)

    count, _, stats, _ = cv2.connectedComponentsWithStats(mask, connectivity=8)

    height, width = mask.shape
    candidates = []
    for label in range(1, count):  # label 0 is the background
        x, y, w, h, area = stats[label]
        if area < config.min_area or area > config.max_area:
            continue
        candidates.append(
            Candidate(
                x1=max(0, x - config.pad),
                y1=max(0, y - config.pad),
                x2=min(width, x + w + config.pad),
                y2=min(height, y + h + config.pad),
                area=int(area),
            )
        )
    return candidates
